version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # SSH秘密鍵を読み込み、SSHエージェントに追加（CircleCIのProjectSettings->SSH KeysでSSHキーを登録）
      - add_ssh_keys:
          fingerprints:
            - "SHA256:nnNqEURJazE0vFFj5tlmvPYLRdJKlq9qmcIeSqhGb2Q"

      # VPSのホストキーを追加
      - run:
          name: Add VPS to known_hosts
          command: |
            ssh-keyscan -H ${VPS_IP} >> ~/.ssh/known_hosts

      # VPSにSSH接続してスクリプト実行（CircleCIのProjectSettings->Environment VariablesでVPS_USERとVPS_IPを登録）
      - run:
          name: Execute Deploy Script via SSH
          command: |
            ssh ${VPS_USER}@${VPS_IP} "run"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main # mainブランチにマージ/プッシュした時に起動